package com.xsn.dao;

import com.xsn.dataobject.GoodsStockDO;
import com.xsn.dataobject.GoodsStockDOExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GoodsStockDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated Sun Feb 23 13:47:52 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated Sun Feb 23 13:47:52 CST 2020
     */
    int insert(GoodsStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated Sun Feb 23 13:47:52 CST 2020
     */
    int insertSelective(GoodsStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated Sun Feb 23 13:47:52 CST 2020
     */
    List<GoodsStockDO> selectByExample(GoodsStockDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated Sun Feb 23 13:47:52 CST 2020
     */
    GoodsStockDO selectByPrimaryKey(Integer id);
    GoodsStockDO selectByGoodsId(Integer goods_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated Sun Feb 23 13:47:52 CST 2020
     */
    int updateByPrimaryKeySelective(GoodsStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated Sun Feb 23 13:47:52 CST 2020
     */
    int updateByPrimaryKey(GoodsStockDO record);
    int desStorck(@Param("goodsId")Integer goodsId, @Param("amount")Integer amount);

}