package com.xsn.dao;

import com.xsn.dataobject.OrderInfoDO;
import com.xsn.dataobject.OrderInfoDOExample;
import java.util.List;

public interface OrderInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sun Feb 23 23:01:36 CST 2020
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sun Feb 23 23:01:36 CST 2020
     */
    int insert(OrderInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sun Feb 23 23:01:36 CST 2020
     */
    int insertSelective(OrderInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sun Feb 23 23:01:36 CST 2020
     */
    List<OrderInfoDO> selectByExample(OrderInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sun Feb 23 23:01:36 CST 2020
     */
    OrderInfoDO selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sun Feb 23 23:01:36 CST 2020
     */
    int updateByPrimaryKeySelective(OrderInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sun Feb 23 23:01:36 CST 2020
     */
    int updateByPrimaryKey(OrderInfoDO record);
}