package com.xsn.dao;

import com.xsn.dataobject.PromoDO;
import com.xsn.dataobject.PromoDOExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PromoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Mon Mar 02 16:08:56 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Mon Mar 02 16:08:56 CST 2020
     */
    int insert(PromoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Mon Mar 02 16:08:56 CST 2020
     */
    int insertSelective(PromoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Mon Mar 02 16:08:56 CST 2020
     */
    List<PromoDO> selectByExample(PromoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Mon Mar 02 16:08:56 CST 2020
     */
    PromoDO selectByPrimaryKey(Integer id);
    PromoDO selectByGoodsId(@Param("goodsId")Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Mon Mar 02 16:08:56 CST 2020
     */
    int updateByPrimaryKeySelective(PromoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Mon Mar 02 16:08:56 CST 2020
     */
    int updateByPrimaryKey(PromoDO record);
}