package com.xsn.dataobject;

public class GoodsStockDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_stock.id
     *
     * @mbg.generated Sun Feb 23 13:47:52 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_stock.stock
     *
     * @mbg.generated Sun Feb 23 13:47:52 CST 2020
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_stock.goods_id
     *
     * @mbg.generated Sun Feb 23 13:47:52 CST 2020
     */
    private Integer goodsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_stock.id
     *
     * @return the value of goods_stock.id
     *
     * @mbg.generated Sun Feb 23 13:47:52 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_stock.id
     *
     * @param id the value for goods_stock.id
     *
     * @mbg.generated Sun Feb 23 13:47:52 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_stock.stock
     *
     * @return the value of goods_stock.stock
     *
     * @mbg.generated Sun Feb 23 13:47:52 CST 2020
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_stock.stock
     *
     * @param stock the value for goods_stock.stock
     *
     * @mbg.generated Sun Feb 23 13:47:52 CST 2020
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_stock.goods_id
     *
     * @return the value of goods_stock.goods_id
     *
     * @mbg.generated Sun Feb 23 13:47:52 CST 2020
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_stock.goods_id
     *
     * @param goodsId the value for goods_stock.goods_id
     *
     * @mbg.generated Sun Feb 23 13:47:52 CST 2020
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }
}