package com.xsn.dataobject;

import java.math.BigDecimal;
import java.util.Date;

public class PromoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.id
     *
     * @mbg.generated Mon Mar 02 16:08:56 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.promo_name
     *
     * @mbg.generated Mon Mar 02 16:08:56 CST 2020
     */
    private String promoName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.start_time
     *
     * @mbg.generated Mon Mar 02 16:08:56 CST 2020
     */
    private Date startTime;
    private Date endTime;

    public Date getEndTime() {
        return endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.goods_id
     *
     * @mbg.generated Mon Mar 02 16:08:56 CST 2020
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.promo_goods_price
     *
     * @mbg.generated Mon Mar 02 16:08:56 CST 2020
     */
    private BigDecimal promoGoodsPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo.id
     *
     * @return the value of promo.id
     *
     * @mbg.generated Mon Mar 02 16:08:56 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo.id
     *
     * @param id the value for promo.id
     *
     * @mbg.generated Mon Mar 02 16:08:56 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo.promo_name
     *
     * @return the value of promo.promo_name
     *
     * @mbg.generated Mon Mar 02 16:08:56 CST 2020
     */
    public String getPromoName() {
        return promoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo.promo_name
     *
     * @param promoName the value for promo.promo_name
     *
     * @mbg.generated Mon Mar 02 16:08:56 CST 2020
     */
    public void setPromoName(String promoName) {
        this.promoName = promoName == null ? null : promoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo.start_time
     *
     * @return the value of promo.start_time
     *
     * @mbg.generated Mon Mar 02 16:08:56 CST 2020
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo.start_time
     *
     * @param startTime the value for promo.start_time
     *
     * @mbg.generated Mon Mar 02 16:08:56 CST 2020
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo.goods_id
     *
     * @return the value of promo.goods_id
     *
     * @mbg.generated Mon Mar 02 16:08:56 CST 2020
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo.goods_id
     *
     * @param goodsId the value for promo.goods_id
     *
     * @mbg.generated Mon Mar 02 16:08:56 CST 2020
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo.promo_goods_price
     *
     * @return the value of promo.promo_goods_price
     *
     * @mbg.generated Mon Mar 02 16:08:56 CST 2020
     */
    public BigDecimal getPromoGoodsPrice() {
        return promoGoodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo.promo_goods_price
     *
     * @param promoGoodsPrice the value for promo.promo_goods_price
     *
     * @mbg.generated Mon Mar 02 16:08:56 CST 2020
     */
    public void setPromoGoodsPrice(BigDecimal promoGoodsPrice) {
        this.promoGoodsPrice = promoGoodsPrice;
    }
}